openapi: 3.1.0
info:
  title: Frontend API Client Interface
  version: 1.0.0
  description: |
    TypeScript API client interface for ChatKit frontend communicating with backend orchestrator.

    All endpoints require authentication token in Authorization header.

servers:
  - url: http://localhost:8000
    description: Local backend
  - url: https://api.example.com
    description: Production backend

paths:
  /api/v1/agents/orchestrator/invoke:
    post:
      summary: Send message to orchestrator agent
      operationId: invokeOrchestrator
      tags:
        - Agent API
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrchestratorRequest'
      responses:
        '200':
          description: Agent response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrchestratorResponse'
        '401':
          description: Unauthorized - session expired
        '500':
          description: Server error

  /api/v1/conversations:
    get:
      summary: List user conversations
      operationId: listConversations
      tags:
        - Conversations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'

    post:
      summary: Create new conversation
      operationId: createConversation
      tags:
        - Conversations
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 255
      responses:
        '201':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

  /api/v1/conversations/{conversationId}/messages:
    get:
      summary: Get messages for conversation
      operationId: getMessages
      tags:
        - Messages
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    OrchestratorRequest:
      type: object
      required:
        - request
        - user_id
        - application_domain
      properties:
        request:
          type: string
          description: User message text
        user_id:
          type: string
        conversation_id:
          type: string
          nullable: true
        application_domain:
          type: string
          default: "todo"

    OrchestratorResponse:
      type: object
      required:
        - execution_id
        - intent
        - entities
        - reasoning_trace
        - status
      properties:
        execution_id:
          type: string
        intent:
          type: object
          properties:
            type:
              type: string
            confidence:
              type: number
        entities:
          type: array
          items:
            type: object
        selected_tool:
          type: object
          nullable: true
          properties:
            tool_name:
              type: string
            confidence:
              type: number
            parameters:
              type: object
        tool_result:
          type: object
          nullable: true
        reasoning_trace:
          type: array
          items:
            type: object
        status:
          type: string
          enum: [success, clarification_needed, failure]

    Conversation:
      type: object
      required:
        - conversation_id
        - user_id
        - title
        - created_at
        - updated_at
      properties:
        conversation_id:
          type: string
        user_id:
          type: string
        title:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Message:
      type: object
      required:
        - message_id
        - conversation_id
        - role
        - content
        - timestamp
      properties:
        message_id:
          type: string
        conversation_id:
          type: string
        role:
          type: string
          enum: [user, agent]
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        tool_calls:
          type: array
          nullable: true
          items:
            type: object
            properties:
              tool_name:
                type: string
              parameters:
                type: object
              result:
                type: object
                nullable: true
              error:
                type: string
                nullable: true
              status:
                type: string
                enum: [success, failure]
